version: '3.3'

services:
  web:
    build:
      context: "."
      args:
        - "RAILS_ENV=${RAILS_ENV:-production}"
        - "NODE_ENV=${NODE_ENV:-production}"
    env_file:
      - ".env"
    restart: "unless-stopped"
    stop_grace_period: "3s"
    tty: true
    volumes:
      - "./public:/app/public"
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl -f http://localhost:8000/up || exit 1"
      interval: 1m
      timeout: 3s
      retries: 3
