# Using AWS RDS with pg

default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
